version: "3"
services:
  nodestatus:
    image: cokemine/nodestatus
    restart: always

    environment:
      PORT: 35601
      VERBOSE: "true"
      THEME: "hotaru-theme"
      PING_INTERVAL: 30

      USE_PUSH: "false"
      USE_IPC: "true"
      USE_WEB: "true"

      WEB_USERNAME: ${myuser}
      WEB_PASSWORD: ${mypass}
      WEB_SECRET: ${mypass2}

      PUSH_TIMEOUT: 30
      PUSH_DELAY: 15

      TGBOT_TOKEN: ""
      TGBOT_CHATID: ""
      TGBOT_PROXY: ""
      TGBOT_WEBHOOK: ""

    volumes:
      - nodestatus-sto:/usr/local/NodeStatus/server
      - /tmp:/tmp:rw

    ports:
      - "35601:35601"
volumes:
  nodestatus-sto:

